import {
  faPoo,
  faMusic,
  faUser,
  faPhone,
  faStar,
  faFaceSmile,
  faHippo,
  faTruck,
  faHeart,
  faCameraRetro,
  faCloud,
  faCar,
  faGhost,
  faUmbrella,
  faGift,
  faHeadphones,
  faBook,
  faDroplet,
  faPlane,
  faVideo,
  faHand,
  faMoneyBill,
  faLemon,
  faBicycle,
  faTree,
} from "@fortawesome/free-solid-svg-icons";

import { ImageCardType } from "./types";

export const images: ImageCardType[] = [
  { id: 1, icon: faPoo, name: "Poo" },
  { id: 2, icon: faMusic, name: "Music" },
  { id: 3, icon: faUser, name: "User" },
  { id: 4, icon: faPhone, name: "Phone" },
  { id: 5, icon: faStar, name: "Star" },
  { id: 6, icon: faFaceSmile, name: "FaceSmile" },
  { id: 7, icon: faHippo, name: "Hippo" },
  { id: 8, icon: faTruck, name: "Truck" },
  { id: 9, icon: faHeart, name: "Heart" },
  { id: 10, icon: faCameraRetro, name: "CameraRetro" },
  { id: 11, icon: faCloud, name: "Cloud" },
  { id: 12, icon: faCar, name: "Car" },
  { id: 13, icon: faGhost, name: "Ghost" },
  { id: 14, icon: faUmbrella, name: "Umbrella" },
  { id: 15, icon: faGift, name: "Gift" },
  { id: 16, icon: faHeadphones, name: "Headphones" },
  { id: 17, icon: faBook, name: "Book" },
  { id: 18, icon: faDroplet, name: "Droplet" },
  { id: 19, icon: faVideo, name: "Video" },
  { id: 20, icon: faHand, name: "Hand" },
  { id: 21, icon: faMoneyBill, name: "MoneyBill" },
  { id: 22, icon: faLemon, name: "Lemon" },
  { id: 23, icon: faBicycle, name: "Bicycle" },
  { id: 24, icon: faTree, name: "Tree" },
];
