import {
  faPoo,
  faMusic,
  faUser,
  faPhone,
  faStar,
  faFaceSmile,
  faHippo,
  faTruck,
  faHeart,
  faCameraRetro,
  faCloud,
  faCar,
  faGhost,
  faUmbrella,
  faGift,
  faHeadphones,
  faBook,
  faDroplet,
  faVideo,
  faHand,
  faMoneyBill,
  faLemon,
  faBicycle,
  faTree,
  faPlane,
  faWandMagicSparkles,
  faEarthAmericas,
  faPalette,
  faGamepad,
  faSun,
  faFish,
  faBug,
  faMoon,
  faLaptop,
  faShip,
  faMotorcycle,
  faSeedling,
  faTrain,
  faHammer,
  faTrophy,
  faRobot,
  faCrown,
  faDragon,
  faFingerprint,
  faBaby,
  faOtter,
  faKiwiBird,
  faYinYang,
  faVolleyball,
  faTableTennisPaddleBall,
  faSpider,
  faSnowman,
  faShrimp,
  faRibbon,
  faRainbow,
  faBaseball,
  faBasketball,
  faPeace,
  faFootball,
  faDog,
} from "@fortawesome/free-solid-svg-icons";

import { ImageCardType } from "./types";

export const images: ImageCardType[] = [
  { id: 1, icon: faPoo, name: "Poo" },
  { id: 2, icon: faMusic, name: "Music" },
  { id: 3, icon: faUser, name: "User" },
  { id: 4, icon: faPhone, name: "Phone" },
  { id: 5, icon: faStar, name: "Star" },
  { id: 6, icon: faFaceSmile, name: "FaceSmile" },
  { id: 7, icon: faHippo, name: "Hippo" },
  { id: 8, icon: faTruck, name: "Truck" },
  { id: 9, icon: faHeart, name: "Heart" },
  { id: 10, icon: faCameraRetro, name: "CameraRetro" },
  { id: 11, icon: faCloud, name: "Cloud" },
  { id: 12, icon: faCar, name: "Car" },
  { id: 13, icon: faGhost, name: "Ghost" },
  { id: 14, icon: faUmbrella, name: "Umbrella" },
  { id: 15, icon: faGift, name: "Gift" },
  { id: 16, icon: faHeadphones, name: "Headphones" },
  { id: 17, icon: faBook, name: "Book" },
  { id: 18, icon: faDroplet, name: "Droplet" },
  { id: 19, icon: faVideo, name: "Video" },
  { id: 20, icon: faHand, name: "Hand" },
  { id: 21, icon: faMoneyBill, name: "MoneyBill" },
  { id: 22, icon: faLemon, name: "Lemon" },
  { id: 23, icon: faBicycle, name: "Bicycle" },
  { id: 24, icon: faTree, name: "Tree" },
  { id: 25, icon: faPlane, name: "Plane" },
  { id: 26, icon: faWandMagicSparkles, name: "MagicWand" },
  { id: 27, icon: faEarthAmericas, name: "Earth" },
  { id: 28, icon: faPalette, name: "Palette" },
  { id: 29, icon: faGamepad, name: "Gamepad" },
  { id: 30, icon: faSun, name: "Sun" },
  { id: 31, icon: faFish, name: "Fish" },
  { id: 32, icon: faBug, name: "Bug" },
  { id: 33, icon: faMoon, name: "Moon" },
  { id: 34, icon: faLaptop, name: "Laptop" },
  { id: 35, icon: faShip, name: "Ship" },
  { id: 36, icon: faMotorcycle, name: "Motorcycle" },
  { id: 37, icon: faSeedling, name: "Seedling" },
  { id: 38, icon: faTrain, name: "Train" },
  { id: 39, icon: faHammer, name: "Hammer" },
  { id: 40, icon: faTrophy, name: "Trophy" },
  { id: 41, icon: faRobot, name: "Robot" },
  { id: 42, icon: faCrown, name: "Crown" },
  { id: 43, icon: faDragon, name: "Dragon" },
  { id: 44, icon: faFingerprint, name: "Fingerprint" },
  { id: 45, icon: faBaby, name: "Baby" },
  { id: 46, icon: faOtter, name: "Otter" },
  { id: 47, icon: faKiwiBird, name: "KiwiBird" },
  { id: 48, icon: faYinYang, name: "YinYang" },
  { id: 49, icon: faVolleyball, name: "Volleyball" },
  { id: 50, icon: faTableTennisPaddleBall, name: "TableTennis" },
  { id: 51, icon: faSpider, name: "Spider" },
  { id: 52, icon: faSnowman, name: "Snowman" },
  { id: 53, icon: faShrimp, name: "Shrimp" },
  { id: 54, icon: faRibbon, name: "Ribbon" },
  { id: 55, icon: faRainbow, name: "Rainbow" },
  { id: 56, icon: faBaseball, name: "Baseball" },
  { id: 57, icon: faBasketball, name: "Basketball" },
  { id: 58, icon: faPeace, name: "Peace" },
  { id: 59, icon: faFootball, name: "Football" },
  { id: 60, icon: faDog, name: "Dog" },
];
