import Head from "next/head";
import { useState, useEffect } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSun, faMoon } from "@fortawesome/free-solid-svg-icons";
import { useTheme } from "next-themes";

import Hero from "../components/Hero";
import ImageCard from "../components/ImageCard";
import { images } from "../images";

export default function Home() {
  const { theme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  console.log(theme);

  return (
    <div className="w-full min-h-screen flex flex-col bg-black dark:bg-white text-white dark:text-black px-4 items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="w-full h-16 flex justify-between items-center">
        <h1 className="text-lg">Black and White images</h1>

        <button
          className="w-8 h-8 dark:bg-blue-100 rounded-lg :bg-slate-800 flex items-center justify-center hover:ring-2 ring-blue-400 transition-all duration-300 focus:outline-none"
          onClick={() => setTheme(theme === "light" ? "dark" : "light")}
          aria-label="Toggle Dark Mode"
        >
          {theme === "light" ? (
            <FontAwesomeIcon icon={faSun} />
          ) : (
            <FontAwesomeIcon icon={faMoon} />
          )}
        </button>
      </header>

      <main className="flex-1 max-w-screen-xl w-full">
        <Hero />
        <section className="grid grid-cols-3 sm:grid-cols-4 gap-4 auto-cols-max">
          {images.map((image) => (
            <ImageCard image={image} key={image.id} />
          ))}
        </section>
      </main>

      <footer className="h-16 flex items-center">
        Created by Chad Murobayashi
      </footer>
    </div>
  );
}
