import Head from "next/head";
import ImageCard from "../components/ImageCard";
import { images } from "../images";

export default function Home() {
  return (
    <div className="w-full h-screen flex flex-col bg-black text-white px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 className="h-16 flex items-center text-2xl">
          Black and White Images for Babies
        </h1>
      </header>

      <main className="flex-1">
        <div>
          {images.map((image) => (
            <ImageCard image={image} key={image.id} />
          ))}
        </div>
      </main>

      <footer className="h-16 flex items-center">
        Created by Chad Murobayashi
      </footer>
    </div>
  );
}
